name: deepsorf
dependencies:
  - pip:
      - setuptools==69.5.1
      - python=3.14.3
      - pytorch=2.10.0
      - numpy=2.4.3
      - pandas=3.0.2
      - scikit-learn=1.8.0
      - matplotlib=3.10.8
      - seaborn=0.13.2
      - h5py=3.16.0
      - tensorboard=2.20.0
      - joblib=1.5.3
      - tqdm=4.67.3